# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/sdm660-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter beckham evert lake,$(TARGET_DEVICE)),)

endif
